FROM node:6.9.1
RUN npm install -g yarn
WORKDIR /code
COPY package.json package.json
COPY yarn.lock yarn.lock
COPY gulpfile.js gulpfile.js
COPY elm-package.json elm-package.json
RUN yarn
COPY jarbas jarbas
CMD yarn assets
